- name: restart app 
  tags: restart
  hosts: all
  become: true
  vars_files:
  - ./variables.yml
  tasks:
    - name: running docker compose down
      command: sudo docker compose down
      args:
        chdir: "/home/{{ APP_USER }}/"

    - name: running docker compose up
      command: sudo docker compose up -d
      args:
        chdir: "/home/{{ APP_USER }}/"
