#
# this docker compose is meant for local development, for production use the ansible generated docker-compose.yml
#

services:
  postgres:
    image: postgres:17-alpine        
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    secrets:
      - postgres-password
    environment:
      - POSTGRES_DB=ShoppingListDB
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 5

  api:
    build: ./src/
    image: shopping-list-api:latest
    ports:
      - ${APP_PORT:-5011}:8080
    depends_on:
      - postgres
    secrets:
      - postgres-password
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ShoppingListDB
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password

secrets:
  postgres-password:
    file: ./postgres-password.txt