services:
  postgres:
    image: postgres:latest        
    # user: postgres:postgres  todo
    restart: unless-stopped
    ports:
      - "${PUBLIC_DB_PORT}:5432"
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data
    networks:
      - internal-only

  pg-backup:
    image: prodrigestivill/postgres-backup-local:latest
    container_name: pg-backup
    restart: unless-stopped
    # user: postgres:postgres    todo
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      - SCHEDULE=@daily

      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=0
      - BACKUP_KEEP_MONTHS=0
    volumes:
      - ./postgres-backups:/backups
    networks:
      - internal-only
    links:
      - postgres

  api:
    build: ./
    image: shopping-list-api:latest
    restart: unless-stopped
    ports:
      - ${PUBLIC_APP_PORT}:8080
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__ShoppingListDB=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - internal-only
      # - backend

networks:
  internal-only:
    driver: bridge
    # internal: true
  # backend:
  #   driver: bridge