services:
  postgres:
    image: postgres:17-alpine        
    restart: unless-stopped
    ports:
      - "${PUBLIC_DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - internal-only
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 10s
        retries: 5

  pg-backup:
    image: prodrigestivill/postgres-backup-local:17-alpine
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      - SCHEDULE=@daily

      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=0
      - BACKUP_KEEP_MONTHS=0
    volumes:
      - ${POSTGRES_BACKUP_LOCATION}:/backups
    networks:
      - internal-only
    links:
      - postgres

  api:
    build: ./
    image: shopping-list-api:latest
    user: 1001:1001
    restart: unless-stopped
    ports:
      - ${PUBLIC_APP_PORT}:8080
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__ShoppingListDB=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=postgres;Password=${POSTGRES_PASSWORD}
    networks:
      - internal-only
      - backend

networks:
  internal-only:
    driver: bridge
    # internal: true
  backend:
    driver: bridge